### ISSUE TITLE
RPM packages for RHEL8/CentOS 8

### ISSUE THREAD

**Issue by space88man** [rabbitmq/rabbitmq-server-release#109]
RFE: EL8 packaging

Now RHEL8, OL8 and CentOS 8 are all out, it would be great to have RPM packages for EL8-based distros.

Thank you.

## Current Status [Added by Maintainers]

Unfortunately we are blocked by the AWS AMI availability for CentOS 8. We use VMs for testing  because "Docker-in-Docker" on Concourse has deal breaking limitations for this kind of testing.

**Comment by michaelklishin** [comment]
We will start with producing a CentOS 8 version of our zero dependency Erlang RPM. It is a much smaller task and it would be required for RabbitMQ package testing on CentOS 8.

**Comment by michaelklishin** [comment]
@nih0 suggests the CentOS 7 package works (we expected this, and this was our experience with the Erlang RPM package). Here's a [rabbitmq-users thread](https://groups.google.com/d/msg/rabbitmq-users/1u8W-1Zq0sw/P_DhwNIwBwAJ). Thank you, @nih0.

**Comment by michaelklishin** [comment]
Our [zero dependency Erlang RPM](https://github.com/rabbitmq/erlang-rpm/releases) releases already include RHEL/CentOS 8 packages.

**Comment by michaelklishin** [comment]
Unfortunately we are blocked by the AWS AMI availability for CentOS 8. We use VMs for testing  because "Docker-in-Docker" on Concourse has deal breaking limitations for this kind of testing.

**Comment by michaelklishin** [comment]
This was [addressed](https://dl.bintray.com/rabbitmq/rpm/rabbitmq-server/v3.8.x/el/8/) for `3.8.1` and `3.7.21` releases.
