### ISSUE TITLE
Windows service can look up an outdated Erlang version in the registry

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server-release#117]
See https://github.com/rabbitmq/rabbitmq-server/issues/1969#issuecomment-583469093.

**Comment by lukebakken** [comment]
It is not possible to change the behavior in NSIS. I have created the following documentation improvements to address this scenario: https://github.com/rabbitmq/rabbitmq-website/pull/953

[171866390]
