### ISSUE TITLE
With an RPM installation, running rabbitmq-plugins as rabbitmq user fails

### ISSUE THREAD

**Issue by nirroz93** [rabbitmq/rabbitmq-server-release#118]
With error "Only root or rabbitmq can run rabbitmq-plugins"

the relevant if is 
elif current_user_is_rabbitmq && ! calling_rabbitmq_plugins
in rabbitmq-script-wrapper

not sure why the ! calling_rabbitmq_plugins is required. If it's required, error should say only root can run and not only root or rabbitmq can run

Tried with fresh install (version 3.8.2) on centos7 running /sbin/rabbitmq-plugins list

**Comment by michaelklishin** [comment]
@nirroz93 it is not required in every case but with things such as the RPM and Debian packages, certain files and directories typically have restricted permissions.

@lukebakken @gerhard @dumbbell should we relax this restriction? Running as RabbitMQ's user in those environments makes some sense.

**Comment by lukebakken** [comment]
When running as `rabbitmq`, you won't have write permission to `/etc/rabbitmq`, which is why this condition exists (related to https://github.com/rabbitmq/rabbitmq-server/issues/2234). Listing plugins will work, changing the configuration = 💥

**Comment by michaelklishin** [comment]
Closed due to the lack of activity. If this keeps coming up we will reopen it.

**Comment by lukebakken** [comment]
We can change the check once this PR ships:

https://github.com/rabbitmq/rabbitmq-server/pull/2298
