### ISSUE TITLE
Windows: package latest Erlang installer

### ISSUE THREAD

**Issue by tracker1** [rabbitmq/rabbitmq-server-release#128]
Given the erlang pre-requisite (sitting at 4% download in the Southwest US, and probably going to take an hour) ... It would be nice if you'd tag an #Erlang release and include the dependencies for the latest erlang.

Or reach out to erlang to try to get them to post it to github releases or another cdn... it's the most painful part of installing RabbitMQ, at least in Windows. (aside, I would love to move off this).

**Comment by michaelklishin** [comment]
If the problem comes down not to Erlang Windows package availability but rather to how it is distributed, any user can set up a mirror for Erlang Windows packages (Erlang/OTP is ASL2-licensed) or reach out to the Erlang community on `erlang-questions`. They are just as [un]likely to switch their distribution mechanism and approach to binary packaging (where binary packages are only provided for minor and major releases but not patches) in that case. Our team does not get any special treatment.

**Comment by michaelklishin** [comment]
Another factor at play here is that Erlang binary builds are large and we have learned the hard way that distributing large packages via "free for open source" CDNs or distribution services is quite likely to exceed their [fairly generous] limits. So if we were to re-upload Erlang binary builds for Windows to, say, our Bintray org, we would have to pay for all the traffic or put the availability of our existing packages at risk. Bintray does not offer plans that would fit a small org so it would be significantly more expensive than it may seem at first.

We could upload them to GitHub but so could any other person who runs into the issue of slow downloads.

The most pragmatic short term solution would be to let `erlang-questions` and [bugs.erlang.org](https://bugs.erlang.org/) know that perhaps Windows packages should be distributed via GitHub for its generously provided free CDN, and then upload the latest installer to any blob store you like (S3 or similar) and use that "mirror" in your provisioning automation tooling.

We can try to re-start the conversation with Ericsson and Erlang Solutions about Erlang packaging but honestly, I would not expect any quick resolutions.

**Comment by michaelklishin** [comment]
Filed [ERL-1221](https://bugs.erlang.org/browse/ERL-1221) and [ERL-1222](https://bugs.erlang.org/browse/ERL-1222). I expect no progress on the later one but hey, it took a few minutes to post so I'm willing to take a chance :)

**Comment by tracker1** [comment]
@michaelklishin thank you for this... may just set up an haproxy behind cloudflare that references the main erlaing site... It's really weird how unresponsive the erlang developers are to this issue.
