### ISSUE TITLE
rabbitmq-server-ha.ocf's `wait_sync` checks queues on / vhost only

### ISSUE THREAD

**Issue by vuntz** [rabbitmq/rabbitmq-server-release#22]
It looks to me like `wait_sync` in rabbitmq-server-ha.ocf is broken: the intent is to look if all queues are synchronized, but it only looks at the / vhost (since `rabbitmqctl list_queues` is called without `-p`) and it ignores all other vhosts.

I guess it should iterate over each vhost, or at least there should be a parameter for the resource agent to specify which vhost we care most about.

**Comment by binarin** [comment]
As this script is responsible for managing the whole lifecycle  of a RabbitMQ cluster, there can't be any other vhosts. While you can create them manually, in some worst case scenarios they can be lost.

So you'll need to add a lot more here to have a proper multi-vhost support  =)

**Comment by vuntz** [comment]
@binarin I'm fine with that; then we just miss the ability to specify the vhost that is really used (it's not necessarily /).
