### ISSUE TITLE
Requirements info in README.

### ISSUE THREAD

**Issue by hairyhum** [rabbitmq/rabbitmq-server-release#37]
There was a list of requirements for building a server package on the old website. I cannot find any information about required packages (like `nsis` or `xsltproc`) in this repo, while the new website links to this repo for build instructions. And it looks like requirements have changed for `3.7` compared to `3.6`
Is there a requirements list anywhere?

**Comment by lukebakken** [comment]
For Windows builds via `make package-windows`:

* NSIS - [download](http://nsis.sourceforge.net/Download), add `C:\Program Files (x86)\NSIS` to `PATH`
* `todos` is needed [here](https://github.com/rabbitmq/rabbitmq-server-release/blob/master/Makefile#L269) - [download](https://www.thefreecountry.com/tofrodos/index.shtml)
* `mandoc` - [download](http://embedeo.org/ws/doc/man_windows/)
* `elinks` - available in `msys` via `pacman -S elinks`
* `docbook` - available in `msys` via `pacman -S docbook-xml docbook-xsl`

**Comment by lukebakken** [comment]
Updated Windows instructions are [here](https://gist.github.com/lukebakken/f0323f90291b5e5e7bbbe0287c411171)

**Comment by lukebakken** [comment]
Here is a `Vagrantfile` that will install all necessary deps for building on Linux - https://gist.github.com/lukebakken/84fb0db5618e18caa2839a151ccb5ace

I will add both of my guides to this project's README
