### ISSUE TITLE
CentOS 7 using SELinux may cause file access error during log rotation.

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-server-release#39]
@mliker originally reported in #32:

I am also running into a similar issue on Centos 7 with RabbitMQ installed from the official repo (http://www.rabbitmq.com/releases/rabbitmq-server), installed version is 3.6.10.

Logrotate fails with the following message:
```
/etc/cron.daily/logrotate:

Error: Failed to initialize erlang distribution: {{shutdown,
                                                  {failed_to_start_child,
                                                   auth,
                                                   {{error,
                                                     "Error when reading /var/lib/rabbitmq/.erlang.cookie: eacces"},
                                                    [{auth,init_cookie,0,
                                                      [{file,"auth.erl"},
                                                       {line,286}]},
                                                     {auth,init,1,
                                                      [{file,"auth.erl"},
                                                       {line,140}]},
                                                     {gen_server,init_it,2,
                                                      [{file,
                                                        "gen_server.erl"},
                                                       {line,365}]},
                                                     {gen_server,init_it,6,
                                                      [{file,
                                                        "gen_server.erl"},
                                                       {line,333}]},
                                                     {proc_lib,
                                                      init_p_do_apply,3,
                                                      [{file,"proc_lib.erl"},
                                                       {line,247}]}]}}},
                                                 {child,undefined,
                                                  net_sup_dynamic,
                                                  {erl_distribution,
                                                   start_link,
                                                   [['rabbitmq-cli-24',
                                                     shortnames],
                                                    false]},
                                                  permanent,1000,supervisor,
                                                  [erl_distribution]}}.
error: error running shared postrotate script for '/var/log/rabbitmq/*.log '
```

Digging through audit.log I found a denied access to /var/lib/rabbitmq/.erlang.cookie.

audit2allow suggests the following two selinux rules to be added in order for logrotate for rabbitmq to work:
```bash
root@n2 / # grep rabbitmq /var/log/audit/audit.log.1 | audit2allow 

#============= logrotate_t ==============
allow logrotate_t rabbitmq_var_lib_t:dir { read write };
allow logrotate_t rabbitmq_var_lib_t:file getattr;
```

Should the rabbitmq rpm ship with an updated SELinux policy or is this up to the user to update the policy?

**Comment by lukebakken** [comment]
@mliker -

Running these commands should fix your `eacces`  issue:

```
chcon 'system_u:object_r:rabbitmq_exec_t:s0' /usr/lib64/erlang/erts-8.3.4/bin/beam*
chcon 'system_u:object_r:rabbitmq_exec_t:s0' /usr/lib64/erlang/erts-8.3.4/bin/epmd
```

I'll provide an update with a permanent fix at some point.

**Comment by lukebakken** [comment]
Copying my comment from #32 -

[These two lines](https://github.com/TresysTechnology/refpolicy-contrib/blob/master/rabbitmq.fc#L3-L4) would normally assign a `rabbitmq` specific domain to the erlang executables, but on 64-bit platforms, Erlang installs to `/usr/lib64`. I suspect this is the reason the domain transition used to work but no longer does.

@gvde - Responding to [your comment](https://github.com/rabbitmq/rabbitmq-server-release/issues/32#issuecomment-322683540) -

Yes, I checked labels using `ls -Z` or I would not have suggested the commands [in the comment I made above in this issue ^^^^](https://github.com/rabbitmq/rabbitmq-server-release/issues/39#issuecomment-322605409).

I used a fresh install of CentOS 7 using vagrant (box version `1701.01`), and installed erlang from [here](https://github.com/rabbitmq/erlang-rpm/releases/tag/v19.3.6.2). Some command output (truncated for space reasons):

```
[root@localhost ~]# sestatus
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   enforcing
Mode from config file:          enforcing
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Max kernel policy version:      28

[root@localhost ~]# semanage fcontext --list | fgrep /usr/lib64
/usr/lib64 = /usr/lib

[root@localhost ~]# ls -alZ /usr/lib64/erlang/erts-8.3.5.2/bin
-rwxr-xr-x. root root system_u:object_r:bin_t:s0       beam
-rwxr-xr-x. root root system_u:object_r:bin_t:s0       beam.smp
-rwxr-xr-x. root root system_u:object_r:bin_t:s0       epmd

[root@localhost ~]# restorecon -Rv /usr/lib64/erlang/

[root@localhost ~]# ls -alZ /usr/lib64/erlang/erts-8.3.5.2/bin
-rwxr-xr-x. root root system_u:object_r:bin_t:s0       beam
-rwxr-xr-x. root root system_u:object_r:bin_t:s0       beam.smp
-rwxr-xr-x. root root system_u:object_r:bin_t:s0       epmd
```

As you can see, it appears that the policy that ships out of the box with CentOS 7 does not apply the `rabbitmq_exec_t` domain to these files. It appears that applying this to the system-wide Erlang installation may not be the best practice, anyway (TresysTechnology/refpolicy#114).

I recommend following up with the CentOS project and / or by filing an issue [here](https://github.com/TresysTechnology/refpolicy/issues) to address this.

I will discuss applying [the `chcon` workaround](https://github.com/rabbitmq/rabbitmq-server-release/issues/39#issuecomment-322605409) in RabbitMQ packaging with the team.

**Comment by mliker** [comment]
This worked for me. Thanks for your help @lukebakken 

However, only after I changed from su to sudo in rabbitmqctl since on CentOS there is a pam requirement for a user id to be above 1000 to be able to su and in my installation rabbitmq user has an uid of 991

**Comment by lukebakken** [comment]
@mliker thank you for that information, we may be able to use it going forward. I made [this change](https://github.com/rabbitmq/rabbitmq-server-release/pull/40) for the `3.7.0` (future) release to use `runuser` (if present) instead of `su` as it does not have the same limitations.

If you have a second, could you detail where the "uid > 1000" PAM requirement is applied, or how you diagnosed it?

**Comment by mliker** [comment]
Well when the logrotation of rabbitmq logs failed I went hunting for causes in the logs files and found this:
`/var/log/secure-20170820:Aug 15 03:15:28 n3 su: pam_succeed_if(su:auth): requirement "uid >= 1000" not met by user "rabbitmq"`

After some googling I learned the issue is caused by pam settings. https://centos.org/forums/viewtopic.php?f=51&t=60922

Then confirmed it in my installation:
```
root@n3 ~ # egrep -r 1000 /etc/pam.d/*
/etc/pam.d/fingerprint-auth:account     sufficient    pam_succeed_if.so uid < 1000 quiet
/etc/pam.d/fingerprint-auth-ac:account     sufficient    pam_succeed_if.so uid < 1000 quiet
/etc/pam.d/password-auth:auth        requisite     pam_succeed_if.so uid >= 1000 quiet_success
/etc/pam.d/password-auth:account     sufficient    pam_succeed_if.so uid < 1000 quiet
/etc/pam.d/password-auth-ac:auth        requisite     pam_succeed_if.so uid >= 1000 quiet_success
/etc/pam.d/password-auth-ac:account     sufficient    pam_succeed_if.so uid < 1000 quiet
/etc/pam.d/smartcard-auth:account     sufficient    pam_succeed_if.so uid < 1000 quiet
/etc/pam.d/smartcard-auth-ac:account     sufficient    pam_succeed_if.so uid < 1000 quiet
/etc/pam.d/system-auth:auth        requisite     pam_succeed_if.so uid >= 1000 quiet_success
/etc/pam.d/system-auth:account     sufficient    pam_succeed_if.so uid < 1000 quiet
/etc/pam.d/system-auth-ac:auth        requisite     pam_succeed_if.so uid >= 1000 quiet_success
/etc/pam.d/system-auth-ac:account     sufficient    pam_succeed_if.so uid < 1000 quiet
```

Replacing su with sudo seemed like a nobrainer to me.

Btw. why is sudo not used?

**Comment by lukebakken** [comment]
Thank you very much for that information.

`su` is generally always available on a base system, while `sudo` is not. Some sys admins don't like to add `sudo`, either (it seems). It looks as though `runuser` is becoming more generally available as well, as the latest Ubuntu release has it installed by default.

**Comment by mliker** [comment]
Fair enough and thanks for the explanation.

**Comment by gvde** [comment]
For CentOS 7 runuser is in the same package as su, thus it's a good option for CentOS/RHEL 7.

**Comment by gvde** [comment]
There is a misunderstanding about the uid >= 1000 in the pam configuration. The purpose of this is to prevent accounts with uid < 1000 be authenticated against the following pam modules, usually ldap or sssd, i.e. modules supporting external authentication. That's all.

This means your error "su: pam_succeed_if(su:auth): requirement "uid >= 1000" not met by user "rabbitmq"" says that no pam module before that line was able to sufficiently authenticate the account. Most likely reason for this is probably that you did not use locauthorize with authconfig during setup, i.e. local user accounts won't work. The pam configuration for su is missing the pam_localuser.so calls to allow accounts in auth and account sections...

**Comment by lukebakken** [comment]
@gvde - thank you for the clarification.

I still was not able to get `su` to work in the context of a cron-executed logrotate job due to SELinux policies. `runuser` works I suspect due to the fact that it is not set-uid root like `su` is and thus is subject to different SELinux policies.

**Comment by gvde** [comment]
The pam configuration for su calls pam_rootok first. According to the man page it checks the real uid of the process for 0 and if it is 0 the call is accepted.

It is unclear to me why the real uid of the process of a root cron job fails this pam module. For a root cron job it should be 0 regardless whether the executable is setuid root or not. I don't really understand it.

For the purpose of the rabbitmqctl script runuser seems to be the correct program to use as it can't ask for the password and can only be used by root...

**Comment by mliker** [comment]
Here is the whole context from /var/log/secure:
```
Aug 15 03:15:28 n3 su: pam_unix(su:auth): auth could not identify password for [rabbitmq]
Aug 15 03:15:28 n3 su: pam_succeed_if(su:auth): requirement "uid >= 1000" not met by user "rabbitmq"
```

And here is what was logged in /var/log/messages:
```
Aug 15 03:15:28 n3 su: FAILED SU (to rabbitmq) root on none
```

**Comment by gvde** [comment]
The error messages itself aren't very helpful unless you post the pam configuration for su. See /etc/pam.d/su

If it is a "normal" pam configuration, both errors in your /var/log/secure are misleading because the actual problem is the failure of pam_rootok before. If it was working as excepted (i.e. as run by root tty) it would never call pam_unix nor the pam_succeed_if.

Thus, those errors don't show the real problem. The problem is before with the pam_rootok module. If it's CentOS 7 the pam_rootok module should support a debug option which would log the relevant failure.

If pam_rootok fails the "normal" centos7 pam configuration requires to enter the password which causes the first error because there is no tty. You should see the same error if you set up a non-root/standard local user cronjob calling su.

**Comment by gvde** [comment]
I have a server with those two packages installed:
```
erlang-20.0.4-1.el6.x86_64
rabbitmq-server-3.6.11-1.el7.noarch
```
The only erlang selinux record is this:
```
# semanage fcontext --list | fgrep erlang
/usr/lib/erlang/erts.*/bin(/.*)?                   all files          system_u:object_r:bin_t:s0 
```
The beam and epmd exec_t from those two lines linked above don't exist:
```
# seinfo -t | fgrep rabbitmq
   rabbitmq_client_packet_t
   rabbitmq_var_lib_t
   rabbitmq_var_run_t
   rabbitmq_unit_file_t
   rabbitmq_initrc_exec_t
   rabbitmq_exec_t
   rabbitmq_var_lock_t
   rabbitmq_var_log_t
   rabbitmq_server_packet_t
   rabbitmq_port_t
   rabbitmq_t
```
I have added a selinux records for those two chcon lines from above:
```
# semanage fcontext -a -t rabbitmq_exec_t '/usr/lib/erlang/erts.*/bin/beam(.*)?'
# semanage fcontext -a -t rabbitmq_exec_t '/usr/lib/erlang/erts.*/bin/epmd'
# restorecon -R -v /usr/lib64/erlang/erts-9.0.4/bin/
restorecon reset /usr/lib64/erlang/erts-9.0.4/bin/beam.smp context system_u:object_r:bin_t:s0->system_u:object_r:rabbitmq_exec_t:s0
restorecon reset /usr/lib64/erlang/erts-9.0.4/bin/epmd context system_u:object_r:bin_t:s0->system_u:object_r:rabbitmq_exec_t:s0
```
As you can see the equality rule /usr/lib64 = /usr/lib works just fine here.

However, I don't think it's a good idea to modify selinux contexts from another rpm. beam and epmd is installed from erlang. The erlang rpm must set the selinux contexts. Thus, the erlang rpm must set the selinux context and thus the rabbitmq_exec_t must exist before erlang is installed, making rabbitmq a dependency of erlang.

I guess making the domain transition with the erlang bins is just to late. The transition needs to be made before beam or epmd is called, i.e. the script that calls those must have made the transition.

**Comment by lukebakken** [comment]
Pull requests #40 and #45 have addressed this issue as best we can, by using `runuser` instead of `su` when it is available.

As I [explained in a previous comment](https://github.com/rabbitmq/rabbitmq-server-release/issues/39#issuecomment-322792796) the SELinux policies that ship with CentOS and other distros are problematic and have their own issues (TresysTechnology/refpolicy#114). I suggest following up there or with the CentOS maintainers.

The RabbitMQ team does not want to modify SELinux policies via the packages we ship, nor do we believe system administrators would want us to. Thanks!

**Comment by gvde** [comment]
Well, you should not modified SELinux policies installed from other packages. Of course, you can set selinux policies in your packages for your files in any way you want. logrotate calls

`/usr/sbin/rabbitmqctl rotate_logs`

If I understand the code correctly it will call rabbitmqctl in /usr/lib/rabbitmq/lib/rabbitmq_server-3.6.11/sbin here on my CentOS 7 server.

```
# ls -lZ /usr/lib/rabbitmq/lib/rabbitmq_server-3.6.11/sbin
-rwxr-xr-x. root root system_u:object_r:lib_t:s0       rabbitmqctl
-rwxr-xr-x. root root system_u:object_r:lib_t:s0       rabbitmq-defaults
-rwxr-xr-x. root root system_u:object_r:lib_t:s0       rabbitmq-env
-rwxr-xr-x. root root system_u:object_r:lib_t:s0       rabbitmq-plugins
-rwxr-xr-x. root root system_u:object_r:rabbitmq_exec_t:s0 rabbitmq-server
```

Thus, if I am not mistaken (haven't had time to test this, yet) you could apply the label rabbitmq_exec_t to rabbitmqctl to make the domain transition at that place. Then there is no need to relabel erlang files...

Of course, I don't know what other security implications that change might have...

**Comment by michaelklishin** [comment]
@gvde our package files are under https://github.com/rabbitmq/rabbitmq-server-release/tree/master/packaging. Would you be interested in submitting a PR to demonstrate the idea?

**Comment by mouchar** [comment]
Well, after brief investigation I have found https://bugzilla.redhat.com/show_bug.cgi?id=1413775 - so it seems that Fedora team is aware of the problem. When it gets fixed, the fix will find its way (sooner or later) to all derived repos (RHEL, CentOS et al).
However, the fix itself appears to be a bit stale - see fedora-selinux/selinux-policy-contrib#15
Author has chosen a bit complicated solution, while other guy removed the file context setup for rabbitmqctl a long time ago... (see fedora-selinux/selinux-policy-contrib@3969696)

**Comment by lukebakken** [comment]
@mouchar - thanks for that info.

We have done what we can to help resolve this (rabbitmq/rabbitmq-server-release#40). If someone wishes to provide a PR or guidance as to how RabbitMQ packaging can address SELinux issues, please re-open this issue.
