### ISSUE TITLE
RabbitMQ can fail to start if network interfaces are not yet up

### ISSUE THREAD

**Issue by yilas** [rabbitmq/rabbitmq-server-release#43]
Hi,

The RabbitMQ server does not start at the boot of a VM. Indeed, the network service is not finished yet when the rabbitmq-server starts. It means that the network interfaces are not UP when the daemon starts.

Here are some logs during the start of services :

```
Aug 29 15:34:18 XXXXXXXXXXXXXXXXX rabbitmq-server[788]: ++ local 'IFS=
Aug 29 15:34:18 XXXXXXXXXXXXXXXXX rabbitmq-server[788]: '
Aug 29 15:34:18 XXXXXXXXXXXXXXXXX rabbitmq-server[788]: +++ tr : '\n'
Aug 29 15:34:18 XXXXXXXXXXXXXXXXX rabbitmq-server[788]: +++ echo /usr/lib/rabbitmq/plugins
Aug 29 15:34:18 XXXXXXXXXXXXXXXXX rabbitmq-server[788]: ++ for dir in '$(echo "$path" | tr '\'':'\'' '\''\n'\'')'
Aug 29 15:34:18 XXXXXXXXXXXXXXXXX rabbitmq-server[788]: ++ '[' -d /usr/lib/rabbitmq/plugins ']'
Aug 29 15:34:18 XXXXXXXXXXXXXXXXX rabbitmq-server[788]: ++ return 1
Aug 29 15:34:18 XXXXXXXXXXXXXXXXX rabbitmq-server[788]: ++ ERL_LIBS=
Aug 29 15:34:18 XXXXXXXXXXXXXXXXX rabbitmq-server[788]: ++ '[' '' ']'
Aug 29 15:34:18 XXXXXXXXXXXXXXXXX rabbitmq-server[788]: ++ RABBITMQ_ENV_LOADED=1
Aug 29 15:34:18 XXXXXXXXXXXXXXXXX rabbitmq-server[788]: ++ true
Aug 29 15:34:18 XXXXXXXXXXXXXXXXX rabbitmq-server[788]: + exec /usr/lib/rabbitmq/bin/rabbitmq-server
Aug 29 15:34:18 XXXXXXXXXXXXXXXXX network[807]: Bringing up loopback interface:  [  OK  ]
Aug 29 15:34:18 XXXXXXXXXXXXXXXXX systemd[1]: Started Dynamic System Tuning Daemon.
Aug 29 15:34:19 XXXXXXXXXXXXXXXXX kernel: vmxnet3 0000:0b:00.0 ens192: intr type 3, mode 0, 2 vectors allocated
Aug 29 15:34:19 XXXXXXXXXXXXXXXXX kernel: vmxnet3 0000:0b:00.0 ens192: NIC Link is Up 10000 Mbps
Aug 29 15:34:19 XXXXXXXXXXXXXXXXX crond[871]: (CRON) INFO (running with inotify support)
Aug 29 15:34:19 XXXXXXXXXXXXXXXXX systemd[1]: Started firewalld - dynamic firewall daemon.
Aug 29 15:34:19 XXXXXXXXXXXXXXXXX kernel: ip6_tables: (C) 2000-2006 Netfilter Core Team
Aug 29 15:34:19 XXXXXXXXXXXXXXXXX kernel: Ebtables v2.0 registered
Aug 29 15:34:19 XXXXXXXXXXXXXXXXX kernel: nf_conntrack version 0.5.0 (16384 buckets, 65536 max)
Aug 29 15:34:19 XXXXXXXXXXXXXXXXX kernel: bridge: automatic filtering via arp/ip/ip6tables has been deprecated. Update your scripts to load br_netfilter if you need this.
Aug 29 15:34:19 XXXXXXXXXXXXXXXXX kernel: Netfilter messages via NETLINK v0.30.
Aug 29 15:34:19 XXXXXXXXXXXXXXXXX kernel: ip_set: protocol 6
Aug 29 15:34:19 XXXXXXXXXXXXXXXXX rabbitmq-server[788]: ERROR: epmd error for host XXXXXXXXXXXXXXXXX: address (cannot connect to host/port)
Aug 29 15:34:19 XXXXXXXXXXXXXXXXX systemd[1]: rabbitmq-server.service: main process exited, code=exited, status=1/FAILURE
Aug 29 15:34:20 XXXXXXXXXXXXXXXXX systemd[1]: Cannot find unit for notify message of PID 1357.
Aug 29 15:34:20 XXXXXXXXXXXXXXXXX systemd[1]: Cannot find unit for notify message of PID 1358.
Aug 29 15:34:20 XXXXXXXXXXXXXXXXX systemd[1]: Cannot find unit for notify message of PID 1361.
Aug 29 15:34:20 XXXXXXXXXXXXXXXXX rabbitmqctl[1230]: Stopping and halting node rabbit@XXXXXXXXXXXXXXXXX ...
Aug 29 15:34:20 XXXXXXXXXXXXXXXXX rabbitmqctl[1230]: Error: unable to connect to node rabbit@XXXXXXXXXXXXXXXXX: nodedown
Aug 29 15:34:20 XXXXXXXXXXXXXXXXX rabbitmqctl[1230]: DIAGNOSTICS
Aug 29 15:34:20 XXXXXXXXXXXXXXXXX rabbitmqctl[1230]: ===========
Aug 29 15:34:20 XXXXXXXXXXXXXXXXX rabbitmqctl[1230]: attempted to contact: [rabbit@XXXXXXXXXXXXXXXXX]
Aug 29 15:34:20 XXXXXXXXXXXXXXXXX rabbitmqctl[1230]: rabbit@XXXXXXXXXXXXXXXXX:
Aug 29 15:34:20 XXXXXXXXXXXXXXXXX rabbitmqctl[1230]: * unable to connect to epmd (port 4369) on XXXXXXXXXXXXXXXXX: address (cannot connect to host/port)
Aug 29 15:34:20 XXXXXXXXXXXXXXXXX rabbitmqctl[1230]: current node details:
Aug 29 15:34:20 XXXXXXXXXXXXXXXXX rabbitmqctl[1230]: - node name: 'rabbitmq-cli-58@XXXXXXXXXXXXXXXXX'
Aug 29 15:34:20 XXXXXXXXXXXXXXXXX rabbitmqctl[1230]: - home dir: .
Aug 29 15:34:20 XXXXXXXXXXXXXXXXX rabbitmqctl[1230]: - cookie hash: iSYBjA9VPehmSB31MGQTSQ==
Aug 29 15:34:20 XXXXXXXXXXXXXXXXX systemd[1]: Failed to start RabbitMQ broker.
Aug 29 15:34:20 XXXXXXXXXXXXXXXXX systemd[1]: Unit rabbitmq-server.service entered failed state.
Aug 29 15:34:20 XXXXXXXXXXXXXXXXX systemd[1]: rabbitmq-server.service failed.
```

I suggest to change the "after" to network-online.target instead of network.target in the service file rabbitmq-server.service

**Comment by lukebakken** [comment]
Please provide the following information:

* Linux distribution and version
* RabbitMQ version
* Steps to reproduce or see the same output as you have above

Providing this information will allow us to reproduce this potential issue (and thus fix it) much more quickly.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions of potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing, or at least sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by michaelklishin** [comment]
I suspect that

> rabbitmq-server[788]: ERROR: epmd error for host XXXXXXXXXXXXXXXXX: address (cannot connect to host/port)

is the line that confirms your findings.

**Comment by michaelklishin** [comment]
@StrangeBubble feel free to submit a PR with the idea you have (against the `stable` branch). Thanks.

**Comment by lukebakken** [comment]
Here's an excerpt from [this page](https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/) with regard to `network-online.target`:

> It is strongly recommended not to pull in this target too liberally: for example network server software should generally not pull this in (since server software generally is happy to accept local connections even before any routable network interface is up), it's primary purpose is network client software that cannot operate without network.

@StrangeBubble please share the information I requested as well as your RabbitMQ config. I am interested in which IP addresses you have RMQ configured to listen on. I suspect you have RMQ configured to listen on the external IP only, which may not be up at the point when it starts.

**Comment by yilas** [comment]
Hi,

Sorry for the delay...

* **Linux distribution and version** : Red Hat 7.3

```
# lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: RedHatEnterpriseServer
Description:    Red Hat Enterprise Linux Server release 7.3 (Maipo)
Release:        7.3
Codename:       Maipo

```

* **RabbitMQ version** : 3.6.9

```
# yum info rabbitmq-server-3.6.9-1.el7.noarch
Loaded plugins: product-id, search-disabled-repos, subscription-manager
Installed Packages
Name        : rabbitmq-server
Arch        : noarch
Version     : 3.6.9
Release     : 1.el7
Size        : 5.3 M
Repo        : installed
Summary     : The RabbitMQ server
URL         : http://www.rabbitmq.com/
License     : MPLv1.1 and MIT and ASL 2.0 and BSD
Description : RabbitMQ is an open source multi-protocol messaging broker.
```

* Steps to reproduce or see the same output as you have above : I just add a set -x at the beginning of the script /usr/sbin/rabbitmq-server and use the journalctl to see the startup log.

About the configuration file, the directory /etc/rabbitmq is empty => I guess the daemon is using a default configuration.

**Comment by lukebakken** [comment]
@StrangeBubble - I can't reproduce this using the latest CentOS 7 VM image for vagrant / virtualbox. RabbitMQ starts up fine on a reboot or when starting the VM cold.

Based on the systemd docs that I mention [in this comment](https://github.com/rabbitmq/rabbitmq-server-release/issues/43#issuecomment-326138182), I don't believe we should change to `network-online.target`.

**Comment by xbeastx** [comment]
We catch same problem on our server.
Prerequsites:
- Ubuntu  18.04
- RabbitMQ 3.6.10
- Server has a lot of virtual interfaces (100)

Once on reboot rabbitmq fail with error:
```
$ cat /var/log/rabbitmq/startup_log
ERROR: epmd error for host hostname-example: address (cannot connect to host/port)
```
This hostname specified at /etc/hosts file:
```
$ cat /etc/hosts
127.0.0.1       localhost
192.168.21.64   hostname-example.net    hostname-example
```
192.168.21.64 - external ip address which statically bind on eno2 interface

if we look at journal on that boot:
```$ sudo journalctl -b -o short-iso-precise | grep -E "(eno2|rabbit|Network)" | head  -n 30
2020-06-30T13:04:07.921546+0300 hostname-example kernel: i40e: Intel(R) Ethernet Connection XL710 Network Driver - version 2.1.14-k
2020-06-30T13:04:07.922596+0300 hostname-example kernel: i40e 0000:1c:00.1 eno2: renamed from eth1
2020-06-30T13:04:10.115332+0300 hostname-example systemd[1]: Reached target Network (Pre).
2020-06-30T13:04:10.119239+0300 hostname-example systemd[1]: Starting Network Service...
2020-06-30T13:04:10.181550+0300 hostname-example systemd[1]: Started Network Service.
2020-06-30T13:04:10.186082+0300 hostname-example systemd[1]: Starting Wait for Network to be Configured...
2020-06-30T13:04:10.190576+0300 hostname-example systemd[1]: Starting Network Name Resolution...
2020-06-30T13:04:10.219190+0300 hostname-example systemd-networkd[2298]: eno2: IPv6 successfully enabled
2020-06-30T13:04:10.256168+0300 hostname-example kernel: IPv6: ADDRCONF(NETDEV_UP): eno2: link is not ready
2020-06-30T13:04:10.256215+0300 hostname-example kernel: IPv6: ADDRCONF(NETDEV_CHANGE): eno2: link becomes ready
2020-06-30T13:04:10.441136+0300 hostname-example systemd[1]: Started Network Name Resolution.
2020-06-30T13:04:10.444282+0300 hostname-example systemd[1]: Reached target Network.
2020-06-30T13:04:10.545651+0300 hostname-example systemd[1]: Reached target Host and Network Name Lookups.
2020-06-30T13:04:10.557163+0300 hostname-example systemd[1]: Starting VirtualBox Network Service...
2020-06-30T13:04:10.909608+0300 hostname-example systemd[1]: rabbitmq-server.service: Main process exited, code=exited, status=1/FAILURE
2020-06-30T13:04:11.209352+0300 hostname-example rabbitmq[2609]: Waiting for 'rabbit@hostname-example'
2020-06-30T13:04:11.209660+0300 hostname-example rabbitmq[2609]: pid is 2680
2020-06-30T13:04:11.223761+0300 hostname-example rabbitmq[2609]: Error: process_not_running
2020-06-30T13:04:11.229064+0300 hostname-example systemd[1]: rabbitmq-server.service: Control process exited, code=exited status=70
2020-06-30T13:04:11.229360+0300 hostname-example systemd[1]: rabbitmq-server.service: Failed with result 'exit-code'.
2020-06-30T13:04:12.798949+0300 hostname-example systemd-networkd[2298]: eno2: Link UP
2020-06-30T13:04:12.821600+0300 hostname-example systemd-networkd[2298]: eno2: Gained carrier
2020-06-30T13:04:12.898433+0300 hostname-example systemd-networkd[2298]: eno2: Gained IPv6LL
2020-06-30T13:04:13.485764+0300 hostname-example systemd-networkd[2298]: eno2: Configured
2020-06-30T13:04:13.491006+0300 hostname-example systemd-networkd-wait-online[2419]: managing: eno2
2020-06-30T13:04:13.492236+0300 hostname-example systemd[1]: Started Wait for Network to be Configured.
2020-06-30T13:04:13.495538+0300 hostname-example systemd[1]: Reached target Network is Online.
```

As you  can see rabbitmq-server starting at same time when network still configuring... so **probably**  this is  race condition on configuring interfaces and starting rabbitmq-server.  so my solution will be start rabbitmq-server after network-online.target

**Comment by michaelklishin** [comment]
@xBeAsTx if you have a specific suggestion for, say, the service unit file we [ship with our packages](https://github.com/rabbitmq/rabbitmq-server-release/tree/master/packaging/RPMS/Fedora), your pull request would be considered. In general, RabbitMQ cannot and should not be responsible for coordinating with network interface startup. So if there is a way to address this using systemd dependencies of sorts, we would consider them, otherwise, there isn't much we can do.

RabbitMQ 3.6 has [gone out of support](https://www.rabbitmq.com/versions.html) more than two years ago. We won't be accepting any contributions specific to that series.
