### ISSUE TITLE
Require systemd  >= 218

### ISSUE THREAD

**Issue by sega-yarkin** [rabbitmq/rabbitmq-server-release#54]
It is better to set minimal version of systemd in dependencies at least 218 (systemd >= 218).
We have had an issue with `Type=notify`, systemd lower than 218 and socat in our project.

**Comment by michaelklishin** [comment]
Would it mean we won't be able to support certain distributions? If so, what are they?

**Comment by sega-yarkin** [comment]
The release 218 of systemd is quite old and I think modern releases of popular distributions have newer version. I can not named distributions with older versions, but there could be a bug with `notify` which we faced with: program sends notification, but systemd doesn't handle it right and a starting process is timed out.

**Comment by michaelklishin** [comment]
systemd 218 was released in [December 2014](https://www.freedesktop.org/software/systemd/). CentOS 7 was released [several months earlier](https://en.wikipedia.org/wiki/CentOS#CentOS_releases) and will be supported until 2020.

@sega-yarkin the best we can do is to add the system version requirement for RabbitMQ 3.7.0. Please submit a PR against `master`.

**Comment by lukebakken** [comment]
@sega-yarkin - could you provide information on how to reproduce the issue you see with `Type=notify` and `socat`, or if that issue is documented anywhere? I would like to see if the same issue could affect RabbitMQ.

**Comment by michaelklishin** [comment]
systemd 219 is [used by CentOS starting with 7.2](https://bugzilla.redhat.com/show_bug.cgi?id=1199644).

**Comment by michaelklishin** [comment]
Given that this would cut off CentOS 7.0 support and we do not recall this issue being reported elsewhere in ~ 1 year of systemd support in our packages. I'm afraid we cannot accept this at this time.

Thank you for your time, I have no doubt this information will be useful to someone one day (and not just RabbitMQ users, perhaps).
