### ISSUE TITLE
make -j <num> dist fails, when num > 1

### ISSUE THREAD

**Issue by ioradu** [rabbitmq/rabbitmq-server-release#79]
I am trying to build `rabbitmq-server-3.7.4` (`rabbitmq-server_3.7.4.orig.tar.xz`) from sources.

When I use `make -j 1 dist`, it works perfectly while `make -j 16 dist` (or any number greater than 1), I got the following error:

```bash
Generated escript escript/rabbitmqctl with MIX_ENV=dev
 GEN    escript/rabbitmq-plugins
ln: failed to create hard link ‘escript/rabbitmq-plugins’: File exists
Makefile:88: recipe for target 'escript/rabbitmq-plugins' failed
make[2]: *** [escript/rabbitmq-plugins] Error 1
```

**Comment by michaelklishin** [comment]
Adding `-f` to these [ln calls in rabbitmq-cli Makefile](https://github.com/rabbitmq/rabbitmq-cli/blob/master/Makefile#L63) seems to solve the problem (I tried `-j 4` and `-j 16`).

@dumbbell @hairyhum is that a solution you'd agree with? I can submit a PR if so.

**Comment by dumbbell** [comment]
I committed the following patch to solve this problem which happened in CI as well recently:
rabbitmq/rabbitmq-cli@be71239

The `-f` flag would work on Unix and I considered it, but I don't know about Windows. I admit I didn't bother testing on this system at that time, that's one of the reasons I went with rm(1) instead.

The patch isn't in any release for now. It will be part pf 3.7.5.
