### ISSUE TITLE
CentOS 7 / yum: Updating stops rabbitmq-server (instead of restarting)

### ISSUE THREAD

**Issue by AllenJB** [rabbitmq/rabbitmq-server-release#94]
Updating rabbitmq-server on CentOS 7.6 (using the rabbitmq packagecloud repo) when rabbitmq-server is running results in rabbitmq-server being stopped.

While I'm not familiar with reading .spec files, so may have read this wrong, I suspect this is because the update process executes a "stop" (in pre) followed by a "try-restart" (in postun) - the latter has no effect because the service is stopped.

**Comment by lukebakken** [comment]
@AllenJB thanks for the report. It would be great to know exactly what commands you ran to install RabbitMQ initially and perform the upgrade so I can easily reproduce this issue.

@dumbbell - It looks like [`reload-or-restart `](https://www.freedesktop.org/software/systemd/man/systemctl.html#reload-or-restart%20PATTERN%E2%80%A6) should be used [here](https://github.com/rabbitmq/rabbitmq-server-release/blob/master/packaging/RPMS/Fedora/rabbitmq-server.spec#L190-L197). We should check the other packaging scripts.

**Comment by AllenJB** [comment]
I install the packagecloud rabbitmq/erlang and rabbitmq/rabbitmq-server repos using the packagecloud scripts, `yum install rabbitmq-server`, `systemctl enable rabbitmq-server`, `systemctl start rabbitmq-server` (and obviously check it's running). After that, a `yum update` (or a yum-cron update, for which I have email reports enabled) will trigger the issue when an update to rabbitmq-server is available.

On at least 1 server this happens on the only other non-standard repos that are enabled are Remi (PHP 7.2), NewRelic Infrastructure and EPEL. I've double checked and rabbitmq-server and erlang are both only being installed from the packagecloud rabbitmq repos.

I've not noticed this happen if erlang is updated - only when rabbitmq-server is updated.

yum-cron autoupdates can be mitigated by adding the following to `/etc/yum/yum-cron.conf` (`[base]` section):
```
exclude = rabbitmq*
```

**Comment by michaelklishin** [comment]
Are there steps to reasonably reliably reproduce?

**Comment by lukebakken** [comment]
The attached Vagrantfile reproduces this issue - 
[Vagrantfile.txt](https://github.com/rabbitmq/rabbitmq-server-release/files/2937566/Vagrantfile.txt)
